In [92]:
# Install Dependencies
%pip install langchain langchain-openai langchain-community openai
%pip install duckduckgo-search
%pip install tiktoken
%pip install Pillow
%pip install python-dotenv
%pip install pandas

3744.10s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langchain in /home/nagy/.local/lib/python3.10/site-packages (1.2.15)
Requirement already satisfied: langchain-openai in /home/nagy/.local/lib/python3.10/site-packages (1.1.15)
Requirement already satisfied: langchain-community in /home/nagy/.local/lib/python3.10/site-packages (0.4.1)
Requirement already satisfied: openai in /home/nagy/.local/lib/python3.10/site-packages (2.32.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /home/nagy/.local/lib/python3.10/site-packages (from langchain) (1.3.0)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /home/nagy/.local/lib/python3.10/site-packages (from langchain) (1.1.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.33)
Requirement already satisfied: packaging>=23.2.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/lib/python3/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (5.4.1)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /home/nagy/.local/lib/python3.10/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /home/nagy/.local/lib/python3.10/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/nagy/.local/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /home/nagy/.local/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /home/nagy/.local/lib/python3.10/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (4.11.0)
Requirement already satisfied: certifi in /home/nagy/.local/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /home/nagy/.local/lib/python3.10/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (3.3)
Requirement already satisfied: h11>=0.16 in /home/nagy/.local/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /home/nagy/.local/lib/python3.10/site-packages (from openai) (0.12.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /home/nagy/.local/lib/python3.10/site-packages (from openai) (4.67.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (1.3.0)
Requirement already satisfied: regex>=2022.1.18 in /home/nagy/.local/lib/python3.10/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (1.0.4)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (2.0.45)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (2.12.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-community) (2.2.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/nagy/.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/nagy/.local/lib/python3.10/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/nagy/.local/lib/python3.10/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /home/nagy/.local/lib/python3.10/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/nagy/.local/lib/python3.10/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/nagy/.local/lib/python3.10/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/nagy/.local/lib/python3.10/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.6.2)
Requirement already satisfied: greenlet>=1 in /home/nagy/.local/lib/python3.10/site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/nagy/.local/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

3750.06s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: duckduckgo-search in /home/nagy/.local/lib/python3.10/site-packages (8.1.1)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from duckduckgo-search) (8.3.0)
Requirement already satisfied: primp>=0.15.0 in /home/nagy/.local/lib/python3.10/site-packages (from duckduckgo-search) (1.2.3)
Requirement already satisfied: lxml>=5.3.0 in /home/nagy/.local/lib/python3.10/site-packages (from duckduckgo-search) (6.1.0)
Note: you may need to restart the kernel to use updated packages.

3755.97s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tiktoken in /home/nagy/.local/lib/python3.10/site-packages (0.12.0)
Requirement already satisfied: regex>=2022.1.18 in /home/nagy/.local/lib/python3.10/site-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /home/nagy/.local/lib/python3.10/site-packages (from tiktoken) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/nagy/.local/lib/python3.10/site-packages (from requests>=2.26.0->tiktoken) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.26.0->tiktoken) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/nagy/.local/lib/python3.10/site-packages (from requests>=2.26.0->tiktoken) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/nagy/.local/lib/python3.10/site-packages (from requests>=2.26.0->tiktoken) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

3761.91s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Pillow in /home/nagy/.local/lib/python3.10/site-packages (10.4.0)
Note: you may need to restart the kernel to use updated packages.

3767.82s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /home/nagy/.local/lib/python3.10/site-packages (1.2.1)
Note: you may need to restart the kernel to use updated packages.

3773.73s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/nagy/.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/nagy/.local/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/nagy/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: tzdata>=2022.7 in /home/nagy/.local/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [93]:
import os
import csv
import json
import pandas as pd
from datetime import datetime
from typing import Optional

from langchain_openai import ChatOpenAI
from langchain.agents import create_agent
from langchain_core.tools import Tool, tool
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import (
    HumanMessage,
    AIMessage,
    SystemMessage,
    trim_messages
)
from langchain_community.tools import DuckDuckGoSearchRun

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

print("✅ All libraries imported successfully!")

✅ All libraries imported successfully!

In [94]:
# Initialize Language Model

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.2,
    max_tokens=2048
)

print("✅ LLM initialized: gpt-4o-mini")

✅ LLM initialized: gpt-4o-mini

In [95]:
# Search Tool

search = DuckDuckGoSearchRun()

@tool
def hospital_search_tool(query: str) -> str:
    """Search for nearby hospitals and medical facilities for a query."""
    try:
        enhanced_query = f"hospitals clinics medical facilities {query}"
        results = search.run(enhanced_query)
        return f"🏥 Hospital Search Results:\n{results}"
    except Exception as e:
        return f"❌ Search failed: {str(e)}"

print(hospital_search_tool.name)
print(hospital_search_tool.description)
print("\n🔍 Test Search:")
print(hospital_search_tool.invoke("hospitals near Kom Hamada, Behira, Egypt"))

hospital_search_tool
Search for nearby hospitals and medical facilities for a query.

🔍 Test Search:
🏥 Hospital Search Results:
January 19, 2026 - Healthcare in Egypt is based on a pluralistic system, comprising a variety of healthcare providers from the public as well as the private sector. The government ensures basic universal health coverage, although private services are also available for those with the ability to pay. March 1, 2026 - Following is a list of the top hospitals in Egypt as per information available with us. If you have a feedback to share, please use the comment section below 2 weeks ago - Global Medical City Hospital|** Global Medical City .. We care for your well being Med Right For Medical Services ** Our duties are to deliver patient-centricity, latest technology, and top-notch doctors.|MedPharo - Egypt health tourism portal May 5, 2025 - Download the list of Hospitals in Egypt. Smartscrapers provides an accurate directory and the latest data on the number of Hospitals in Egypt 5 days ago - Misr international hospital is a tertiary care hospital, one of the top ranked hospitals in Egypt, since its establishment in 1983, it has been providing medical services through an elite group of professors and consultants, using the latest ...

In [96]:
# CSV Storage Tool

CSV_FILE_PATH = "patient_cases.csv"

CSV_HEADERS = [
    "case_id",
    "timestamp",
    "patient_symptoms",
    "mri_description",
    "ai_summary",
    "recommended_actions",
    "disclaimer"
]

def initialize_csv():
    """Create CSV file with headers if it doesn't exist."""
    if not os.path.exists(CSV_FILE_PATH):
        with open(CSV_FILE_PATH, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=CSV_HEADERS)
            writer.writeheader()
        print(f"✅ CSV file created: {CSV_FILE_PATH}")
    else:
        print(f"📄 CSV file already exists: {CSV_FILE_PATH}")

initialize_csv()

@tool
def csv_storage_tool(case_data: str) -> str:
    """ Stores structured patient case data into a CSV file. Use this tool after generating a case summary to save the record. """
    try:
        data = json.loads(case_data)
        case_id = f"CASE-{datetime.now().strftime('%Y%m%d%H%M%S')}"
        
        row = {
            "case_id": case_id,
            "timestamp": datetime.now().isoformat(),
            "patient_symptoms": data.get("patient_symptoms", "N/A"),
            "mri_description": data.get("mri_description", "N/A"),
            "ai_summary": data.get("ai_summary", "N/A"),
            "recommended_actions": data.get("recommended_actions", "N/A"),
            "disclaimer": "This is not a medical diagnosis. Consult a doctor."
        }
        
        with open(CSV_FILE_PATH, mode='a', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=CSV_HEADERS)
            writer.writerow(row)
        
        return f"✅ Case saved successfully!\n📋 Case ID: {case_id}\n📁 File: {CSV_FILE_PATH}"
    
    except json.JSONDecodeError:
        return "❌ Error: Invalid JSON format. Please provide valid JSON."
    except Exception as e:
        return f"❌ Error saving case: {str(e)}"


test_data = json.dumps({
    "patient_symptoms": "Severe headache, blurred vision",
    "mri_description": "Mild white matter hyperintensities",
    "ai_summary": "Patient presents with neurological symptoms",
    "recommended_actions": "Consult neurologist"
})

print(csv_storage_tool.invoke(test_data))

📄 CSV file already exists: patient_cases.csv
✅ Case saved successfully!
📋 Case ID: CASE-20260424154214
📁 File: patient_cases.csv

In [97]:
# Verify stored data
df = pd.read_csv(CSV_FILE_PATH)
print("📊 Stored Patient Cases:")
print("=" * 60)
df

📊 Stored Patient Cases:
============================================================

,case_id,timestamp,patient_symptoms,mri_description,ai_summary,recommended_actions,disclaimer
0,CASE-20260424145722,2026-04-24T14:57:22.590459,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
1,CASE-20260424145731,2026-04-24T14:57:31.308154,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
2,CASE-20260424145959,2026-04-24T14:59:59.546426,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
3,CASE-20260424150637,2026-04-24T15:06:37.689787,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
4,CASE-20260424151525,2026-04-24T15:15:25.900821,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
5,CASE-20260424152157,2026-04-24T15:21:57.890933,"Sharp chest pain during physical activity, Sho...",Left ventricular ejection fraction: 48% (mildl...,The patient presents with symptoms indicative ...,It is advisable for the patient to consult a c...,This is not a medical diagnosis. Consult a doc...
6,CASE-20260424152214,2026-04-24T15:22:14.428974,Persistent headache for 5 days (left temporal ...,Small area of white matter hyperintensity in t...,The patient presents with a combination of neu...,Consult a neurologist for further evaluation a...,This is not a medical diagnosis. Consult a doc...
7,CASE-20260424152321,2026-04-24T15:23:21.400827,"Persistent lower back pain for 2 weeks, pain r...",No MRI/Scan findings provided,The symptoms described suggest possible issues...,"Consult a healthcare professional, preferably ...",This is not a medical diagnosis. Consult a doc...
8,CASE-20260424152331,2026-04-24T15:23:31.332173,"Persistent lower back pain for 2 weeks, Pain r...",Not provided,The symptoms suggest possible nerve involvemen...,"Consult a healthcare professional, possibly a ...",This is not a medical diagnosis. Consult a doc...
9,CASE-20260424152635,2026-04-24T15:26:35.311464,Persistent headache for 5 days (left temporal ...,Small area of white matter hyperintensity in t...,"The patient's symptoms of persistent headache,...",Consult a neurologist for further evaluation a...,This is not a medical diagnosis. Consult a doc...
10,CASE-20260424154214,2026-04-24T15:42:14.286914,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...

In [98]:
# Message Trimming for Context Optimization

def trim_conversation_messages(messages, max_tokens=2000):
    """ Trims conversation messages to stay within token limits. Keeps the system message and most recent messages. """

    trimmed = trim_messages(
        messages,
        max_tokens=max_tokens,
        strategy="last",
        token_counter=llm,
        include_system=True,
        start_on="human",
    )
    return trimmed

test_messages = [
    SystemMessage(content="You are a medical assistant. Provide helpful and accurate information based on patient symptoms and medical data."),
    HumanMessage(content="I have a headache. It's been getting worse over the past few days."),
    AIMessage(content="Can you describe the headache?, Please provide more details."),
    HumanMessage(content="It's throbbing and on the left side. Provide more details about the pain and any other symptoms you may have."),
    AIMessage(content="How long have you had it?"),
    HumanMessage(content="About 3 days now. Also, I've been feeling nauseous and have had some dizziness."),
]

trimmed = trim_conversation_messages(test_messages, max_tokens=100)
print(f"Original messages: {len(test_messages)}")
print(f"Trimmed messages:  {len(trimmed)}")
for msg in trimmed:
    print(f"  [{msg.__class__.__name__}]: {msg.content[:60]}...")

Original messages: 6
Trimmed messages:  4
  [SystemMessage]: You are a medical assistant. Provide helpful and accurate in...
  [HumanMessage]: It's throbbing and on the left side. Provide more details ab...
  [AIMessage]: How long have you had it?...
  [HumanMessage]: About 3 days now. Also, I've been feeling nauseous and have ...

In [99]:
# Summarization Buffer Memory

class SummaryMemory:
    def __init__(self, max_token_limit: int, memory_key: str, return_messages: bool = True, output_key: str = "output", llm=None):
        self.max_token_limit = max_token_limit
        self.memory_key = memory_key
        self.return_messages = return_messages
        self.output_key = output_key
        self.chat_history = []
        self.summary = ""
        self.llm = llm

    def load_memory_variables(self, inputs=None):
        if self.return_messages:
            return {self.memory_key: self.chat_history}
        return {self.memory_key: self.summary}

    def save_context(self, inputs, outputs):
        self.chat_history.append({"inputs": inputs, "outputs": outputs})

    def clear(self):
        self.chat_history.clear()
        self.summary = ""

memory = SummaryMemory(
    llm=llm,
    max_token_limit=500,
    return_messages=True,
    memory_key="chat_history",
    output_key="output"
 )

print("✅ Summarization Memory initialized")
print(f"   Max token limit: {memory.max_token_limit}")
print(f"   Memory key: {memory.memory_key}")

✅ Summarization Memory initialized
   Max token limit: 500
   Memory key: chat_history

In [100]:
# System Prompt & Agent Prompt Template

SYSTEM_PROMPT = """
You are a Multi-Modal Medical AI Assistant Agent. Your role is to help
analyze patient cases based on text symptoms and MRI/scan descriptions.

## YOUR CAPABILITIES:
1. **Analyze Inputs**: Process text symptoms and MRI/scan descriptions
2. **Generate Case Summary**: Create structured medical case summaries
3. **Provide Safe Medical Insights**: Offer general health information
4. **Hospital Search**: Find nearby hospitals when requested
5. **Store Case Data**: Save structured case records to CSV

## TOOL USAGE RULES:
- Use `hospital_search_tool` when the user asks about finding hospitals,
  clinics, or medical facilities
- Use `csv_storage_tool` after generating a complete case summary to
  store the structured data. Format the data as JSON with keys:
  patient_symptoms, mri_description, ai_summary, recommended_actions

## RESPONSE FORMAT:
When analyzing a case, structure your response as:

### 📋 Case Summary
- **Symptoms**: [list symptoms]
- **MRI/Scan Findings**: [describe findings]

### 🔍 Analysis
[Provide general medical insights about the symptoms and findings]

### 📌 Recommended Actions
[Suggest general next steps like consulting specialists]

### ⚠️ Disclaimer
*This is not a medical diagnosis. Consult a doctor.*

## STRICT CONSTRAINTS:
- ❌ NEVER provide a specific diagnosis
- ❌ NEVER prescribe medications
- ❌ NEVER replace professional medical advice
- ✅ ALWAYS include the disclaimer
- ✅ ALWAYS recommend consulting a healthcare professional
"""

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

print("✅ Prompt template created")

✅ Prompt template created

In [101]:
# Create Agent and Executor

# List of tools
tools = [hospital_search_tool, csv_storage_tool]

# Create the agent graph
agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=SYSTEM_PROMPT
 )

# Keep a backward-compatible name for the rest of the notebook
agent_executor = agent

print("✅ Agent created successfully!")
print(f"   Tools: {[t.name for t in tools]}")
print("   Memory: SummaryMemory")
print("   Max iterations: handled by create_agent")

✅ Agent created successfully!
   Tools: ['hospital_search_tool', 'csv_storage_tool']
   Memory: SummaryMemory
   Max iterations: handled by create_agent

In [102]:
# Multi-Modal Input Processing

class MedicalInputProcessor:
    def __init__(self):
        self.current_case = {
            "text_symptoms": None,
            "mri_description": None
        }
    
    def process_text_input(self, symptoms: str) -> str:
        self.current_case["text_symptoms"] = symptoms
        return symptoms
    
    def process_mri_description(self, mri_desc: str) -> str:
        self.current_case["mri_description"] = mri_desc
        return mri_desc
    
    def build_agent_input(
        self,
        text_symptoms: str,
        mri_description: Optional[str] = None,
        additional_request: Optional[str] = None
    ) -> str:
        self.process_text_input(text_symptoms)
        input_parts = []
        input_parts.append(f"## Patient Symptoms:\n{text_symptoms}")
        
        if mri_description:
            self.process_mri_description(mri_description)
            input_parts.append(f"\n## MRI/Scan Description:\n{mri_description}")
        
        if additional_request:
            input_parts.append(f"\n## Additional Request:\n{additional_request}")
        
        input_parts.append(
            "\nPlease analyze this case, provide a structured summary, "
            "and save the case data."
        )
        
        return "\n".join(input_parts)
    
    def reset(self):
        """Reset current case data."""
        self.current_case = {
            "text_symptoms": None,
            "mri_description": None
        }


input_processor = MedicalInputProcessor()
print("✅ MedicalInputProcessor initialized")

✅ MedicalInputProcessor initialized

In [103]:
# Test Case 1: Basic Symptom Analysis

print("=" * 100)
print("🧪 TEST CASE 1: Basic Symptom Analysis")
print("=" * 100)

# Build input
user_input = input_processor.build_agent_input(
    text_symptoms="""
    - Persistent headache for 5 days (left temporal region)
    - Blurred vision in left eye
    - Mild nausea in the morning
    - Difficulty concentrating
    - Patient age: 45, Male
    """,
    mri_description="""
    Brain MRI Report:
    - Small area of white matter hyperintensity in the left temporal lobe
    - No mass lesion identified
    - No midline shift
    - Ventricles are normal in size
    - No acute infarct on diffusion-weighted imaging
    """
)

response1 = agent_executor.invoke({
    "messages": [{"role": "user", "content": user_input}]
})
response_text = response1.get("output")
if response_text is None and "messages" in response1:
    response_text = response1["messages"][-1].content
if response_text is None:
    response_text = str(response1)

memory.save_context(
    {"input": user_input},
    {"output": response_text}
 )

print("\n" + "=" * 100)
print("📤 AGENT RESPONSE:")
print("=" * 100)
print(response_text)

input_processor.reset()

====================================================================================================
🧪 TEST CASE 1: Basic Symptom Analysis
====================================================================================================

====================================================================================================
📤 AGENT RESPONSE:
====================================================================================================
### 📋 Case Summary
- **Symptoms**: Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
- **MRI/Scan Findings**: Small area of white matter hyperintensity in the left temporal lobe, No mass lesion identified, No midline shift, Ventricles are normal in size, No acute infarct on diffusion-weighted imaging

### 🔍 Analysis
The patient's symptoms of persistent headache, blurred vision, nausea, and difficulty concentrating, combined with the MRI findings of white matter hyperintensity, may suggest a neurological issue that requires further evaluation. The absence of mass lesions and acute infarcts is reassuring, but the hyperintensity could indicate other conditions such as small vessel disease or demyelination. It is important to correlate these findings with clinical symptoms and consider further diagnostic workup or referral to a neurologist.

### 📌 Recommended Actions
Consult a neurologist for further evaluation and management of symptoms and MRI findings.

### ⚠️ Disclaimer
*This is not a medical diagnosis. Consult a doctor.*

The case has been saved successfully! If you need assistance finding a neurologist or a hospital, please let me know.

In [104]:
# Test Case 2: With Hospital Search Request

print("=" * 100)
print("🧪 TEST CASE 2: Case Analysis + Hospital Search")
print("=" * 100)

user_input2 = input_processor.build_agent_input(
    text_symptoms="""
    - Sharp chest pain during physical activity
    - Shortness of breath
    - Occasional dizziness
    - Family history of heart disease
    - Patient age: 55, Female
    """,
    mri_description="""
    Cardiac MRI Summary:
    - Left ventricular ejection fraction: 48% (mildly reduced)
    - Mild left ventricular hypertrophy
    - No pericardial effusion
    - Mild mitral regurgitation noted
    """,
    additional_request="Please also find cardiology hospitals near Chicago, IL"
)

response2 = agent_executor.invoke({
    "messages": [{"role": "user", "content": user_input2}]
})
response_text = response2.get("output")
if response_text is None and "messages" in response2:
    response_text = response2["messages"][-1].content
if response_text is None:
    response_text = str(response2)

memory.save_context(
    {"input": user_input2},
    {"output": response_text}
 )

print("\n" + "=" * 100)
print("📤 AGENT RESPONSE:")
print("=" * 100)
print(response_text)

input_processor.reset()

====================================================================================================
🧪 TEST CASE 2: Case Analysis + Hospital Search
====================================================================================================

====================================================================================================
📤 AGENT RESPONSE:
====================================================================================================
### 📋 Case Summary
- **Symptoms**:
  - Sharp chest pain during physical activity
  - Shortness of breath
  - Occasional dizziness
  - Family history of heart disease
  - Patient age: 55, Female
- **MRI/Scan Findings**:
  - Left ventricular ejection fraction: 48% (mildly reduced)
  - Mild left ventricular hypertrophy
  - No pericardial effusion
  - Mild mitral regurgitation noted

### 🔍 Analysis
The patient presents with symptoms indicative of potential cardiac issues, including sharp chest pain, shortness of breath, and dizziness, particularly during physical activity. The MRI findings show a mildly reduced left ventricular ejection fraction and mild left ventricular hypertrophy, which may suggest underlying heart conditions. The family history of heart disease further elevates the concern for cardiovascular issues.

### 📌 Recommended Actions
It is recommended to consult a cardiologist for further evaluation and management of the symptoms and MRI findings.

### 🏥 Nearby Cardiology Hospitals
- There are opportunities for cardiologists in a three-hospital system located just outside of Chicago, Illinois. This includes positions for non-invasive cardiologists in nearby Indiana, approximately one hour from Chicago.

### ⚠️ Disclaimer
*This is not a medical diagnosis. Consult a doctor.*

In [105]:
# Test Case 3: Text Only (No MRI)

print("=" * 100)
print("🧪 TEST CASE 3: Text-Only Symptom Analysis")
print("=" * 100)

user_input3 = input_processor.build_agent_input(
    text_symptoms="""
    - Persistent lower back pain for 2 weeks
    - Pain radiates to left leg
    - Numbness in left foot
    - Difficulty walking long distances
    - Patient age: 38, Male, Office worker
    """
)

response3 = agent_executor.invoke({
    "messages": [{"role": "user", "content": user_input3}]
})
response_text = response3.get("output")
if response_text is None and "messages" in response3:
    response_text = response3["messages"][-1].content
if response_text is None:
    response_text = str(response3)

memory.save_context(
    {"input": user_input3},
    {"output": response_text}
 )

print("\n" + "=" * 100)
print("📤 AGENT RESPONSE:")
print("=" * 100)
print(response_text)

input_processor.reset()

====================================================================================================
🧪 TEST CASE 3: Text-Only Symptom Analysis
====================================================================================================

====================================================================================================
📤 AGENT RESPONSE:
====================================================================================================
### 📋 Case Summary
- **Symptoms**: Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker
- **MRI/Scan Findings**: Not provided

### 🔍 Analysis
The patient presents with persistent lower back pain that radiates to the left leg, accompanied by numbness in the left foot and difficulty walking long distances. These symptoms may suggest nerve involvement, possibly due to a herniated disc or other spinal issues. The patient's occupation as an office worker may contribute to prolonged sitting, which can exacerbate back pain.

### 📌 Recommended Actions
Consult a healthcare professional for a thorough evaluation, including a physical examination and possibly imaging studies such as an MRI to assess spinal health.

### ⚠️ Disclaimer
*This is not a medical diagnosis. Consult a doctor.*

---

The case data has been saved successfully!

### 🏥 Nearby Hospitals
- **Damanhour Medical National Institute (D.M.N.I)**, Damanhour
- **Specialized MRI Centers in Damanhour**: Damanhour Radiology Centers under the supervision of Prof. Dr. Hany Abada.

For further assistance, consider contacting the hospitals directly for appointments or inquiries.

In [106]:
# View All Stored Cases in CSV

print("📊 All Stored Patient Cases")
print("=" * 100)

df = pd.read_csv(CSV_FILE_PATH)
print(f"Total cases stored: {len(df)}\n")

for idx, row in df.iterrows():
    print(f"📋 {row['case_id']} | {row['timestamp']}")
    print(f"   Symptoms: {row['patient_symptoms'][:80]}...")
    print(f"   MRI: {row['mri_description'][:80]}...")
    print(f"   Summary: {row['ai_summary'][:80]}...")
    print(f"   Actions: {row['recommended_actions'][:80]}...")
    print(f"   Disclaimer: {row['disclaimer']}")
    print("-" * 100)

df

📊 All Stored Patient Cases
====================================================================================================
Total cases stored: 14

📋 CASE-20260424145722 | 2026-04-24T14:57:22.590459
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424145731 | 2026-04-24T14:57:31.308154
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424145959 | 2026-04-24T14:59:59.546426
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424150637 | 2026-04-24T15:06:37.689787
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424151525 | 2026-04-24T15:15:25.900821
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424152157 | 2026-04-24T15:21:57.890933
   Symptoms: Sharp chest pain during physical activity, Shortness of breath, Occasional dizzi...
   MRI: Left ventricular ejection fraction: 48% (mildly reduced), Mild left ventricular ...
   Summary: The patient presents with symptoms indicative of potential cardiac issues, inclu...
   Actions: It is advisable for the patient to consult a cardiologist for further evaluation...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424152214 | 2026-04-24T15:22:14.428974
   Symptoms: Persistent headache for 5 days (left temporal region), Blurred vision in left ey...
   MRI: Small area of white matter hyperintensity in the left temporal lobe, No mass les...
   Summary: The patient presents with a combination of neurological symptoms including persi...
   Actions: Consult a neurologist for further evaluation and management of symptoms, Conside...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424152321 | 2026-04-24T15:23:21.400827
   Symptoms: Persistent lower back pain for 2 weeks, pain radiating to left leg, numbness in ...
   MRI: No MRI/Scan findings provided...
   Summary: The symptoms described suggest possible issues related to the lumbar spine, such...
   Actions: Consult a healthcare professional, preferably a neurologist or orthopedic specia...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424152331 | 2026-04-24T15:23:31.332173
   Symptoms: Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in l...
   MRI: Not provided...
   Summary: The symptoms suggest possible nerve involvement, potentially indicating a hernia...
   Actions: Consult a healthcare professional, possibly a neurologist or orthopedic speciali...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424152635 | 2026-04-24T15:26:35.311464
   Symptoms: Persistent headache for 5 days (left temporal region), Blurred vision in left ey...
   MRI: Small area of white matter hyperintensity in the left temporal lobe, No mass les...
   Summary: The patient's symptoms of persistent headache, blurred vision, and mild nausea, ...
   Actions: Consult a neurologist for further evaluation and possible follow-up imaging or t...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424154214 | 2026-04-24T15:42:14.286914
   Symptoms: Severe headache, blurred vision...
   MRI: Mild white matter hyperintensities...
   Summary: Patient presents with neurological symptoms...
   Actions: Consult neurologist...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424154222 | 2026-04-24T15:42:22.682278
   Symptoms: Persistent headache for 5 days (left temporal region), Blurred vision in left ey...
   MRI: Small area of white matter hyperintensity in the left temporal lobe, No mass les...
   Summary: The patient's symptoms of persistent headache, blurred vision, nausea, and diffi...
   Actions: Consult a neurologist for further evaluation and management of symptoms and MRI ...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424154233 | 2026-04-24T15:42:33.520857
   Symptoms: Sharp chest pain during physical activity, Shortness of breath, Occasional dizzi...
   MRI: Left ventricular ejection fraction: 48% (mildly reduced), Mild left ventricular ...
   Summary: The patient presents with symptoms indicative of potential cardiac issues, inclu...
   Actions: It is recommended to consult a cardiologist for further evaluation and managemen...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------
📋 CASE-20260424154242 | 2026-04-24T15:42:42.578782
   Symptoms: Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in l...
   MRI: Not provided...
   Summary: The patient presents with persistent lower back pain that radiates to the left l...
   Actions: Consult a healthcare professional for a thorough evaluation, including a physica...
   Disclaimer: This is not a medical diagnosis. Consult a doctor.
----------------------------------------------------------------------------------------------------

,case_id,timestamp,patient_symptoms,mri_description,ai_summary,recommended_actions,disclaimer
0,CASE-20260424145722,2026-04-24T14:57:22.590459,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
1,CASE-20260424145731,2026-04-24T14:57:31.308154,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
2,CASE-20260424145959,2026-04-24T14:59:59.546426,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
3,CASE-20260424150637,2026-04-24T15:06:37.689787,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
4,CASE-20260424151525,2026-04-24T15:15:25.900821,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
5,CASE-20260424152157,2026-04-24T15:21:57.890933,"Sharp chest pain during physical activity, Sho...",Left ventricular ejection fraction: 48% (mildl...,The patient presents with symptoms indicative ...,It is advisable for the patient to consult a c...,This is not a medical diagnosis. Consult a doc...
6,CASE-20260424152214,2026-04-24T15:22:14.428974,Persistent headache for 5 days (left temporal ...,Small area of white matter hyperintensity in t...,The patient presents with a combination of neu...,Consult a neurologist for further evaluation a...,This is not a medical diagnosis. Consult a doc...
7,CASE-20260424152321,2026-04-24T15:23:21.400827,"Persistent lower back pain for 2 weeks, pain r...",No MRI/Scan findings provided,The symptoms described suggest possible issues...,"Consult a healthcare professional, preferably ...",This is not a medical diagnosis. Consult a doc...
8,CASE-20260424152331,2026-04-24T15:23:31.332173,"Persistent lower back pain for 2 weeks, Pain r...",Not provided,The symptoms suggest possible nerve involvemen...,"Consult a healthcare professional, possibly a ...",This is not a medical diagnosis. Consult a doc...
9,CASE-20260424152635,2026-04-24T15:26:35.311464,Persistent headache for 5 days (left temporal ...,Small area of white matter hyperintensity in t...,"The patient's symptoms of persistent headache,...",Consult a neurologist for further evaluation a...,This is not a medical diagnosis. Consult a doc...
10,CASE-20260424154214,2026-04-24T15:42:14.286914,"Severe headache, blurred vision",Mild white matter hyperintensities,Patient presents with neurological symptoms,Consult neurologist,This is not a medical diagnosis. Consult a doc...
11,CASE-20260424154222,2026-04-24T15:42:22.682278,Persistent headache for 5 days (left temporal ...,Small area of white matter hyperintensity in t...,"The patient's symptoms of persistent headache,...",Consult a neurologist for further evaluation a...,This is not a medical diagnosis. Consult a doc...
12,CASE-20260424154233,2026-04-24T15:42:33.520857,"Sharp chest pain during physical activity, Sho...",Left ventricular ejection fraction: 48% (mildl...,The patient presents with symptoms indicative ...,It is recommended to consult a cardiologist fo...,This is not a medical diagnosis. Consult a doc...
13,CASE-20260424154242,2026-04-24T15:42:42.578782,"Persistent lower back pain for 2 weeks, Pain r...",Not provided,The patient presents with persistent lower bac...,Consult a healthcare professional for a thorou...,This is not a medical diagnosis. Consult a doc...

In [107]:
# Inspect Conversation Memory

print("🧠 Current Memory State")
print("=" * 100)

memory_data = memory.load_memory_variables({})
history = memory_data.get("chat_history", [])

print("\n📝 Chat History (Summary + Recent Messages):")
print("-" * 100)

if not history:
    print("(empty)")
else:
    for idx, entry in enumerate(history, start=1):
        if isinstance(entry, dict):
            user_text = entry.get("inputs", {}).get("input", "")
            ai_text = entry.get("outputs", {}).get("output", "")
            print(f"\nTurn {idx} User: {user_text[:200]}...")
            print(f"Turn {idx} AI: {ai_text[:200]}...")
        else:
            role = entry.__class__.__name__.replace("Message", "")
            content = getattr(entry, "content", str(entry))
            print(f"\n[{role}]: {content[:200]}...")

if hasattr(memory, 'moving_summary_buffer'):
    print(f"\n\n📄 Moving Summary Buffer:")
    print("-" * 100)
    print(memory.moving_summary_buffer or "Empty")

🧠 Current Memory State
====================================================================================================

📝 Chat History (Summary + Recent Messages):
----------------------------------------------------------------------------------------------------

Turn 1 User: ## Patient Symptoms:

    - Persistent headache for 5 days (left temporal region)
    - Blurred vision in left eye
    - Mild nausea in the morning
    - Difficulty concentrating
    - Patient age: 45...
Turn 1 AI: ### 📋 Case Summary
- **Symptoms**: Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
- **MR...

Turn 2 User: ## Patient Symptoms:

    - Sharp chest pain during physical activity
    - Shortness of breath
    - Occasional dizziness
    - Family history of heart disease
    - Patient age: 55, Female


## ...
Turn 2 AI: ### 📋 Case Summary
- **Symptoms**:
  - Sharp chest pain during physical activity
  - Shortness of breath
  - Occasional dizziness
  - Family history of heart disease
  - Patient age: 55, Female
- **M...

Turn 3 User: ## Patient Symptoms:

    - Persistent lower back pain for 2 weeks
    - Pain radiates to left leg
    - Numbness in left foot
    - Difficulty walking long distances
    - Patient age: 38, Male, Offi...
Turn 3 AI: ### 📋 Case Summary
- **Symptoms**: Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker
- *...

In [108]:
# Message Trimming Demonstration

print("✂️ Message Trimming Demonstration")
print("=" * 100)

# Simulate a long conversation
long_conversation = [
    SystemMessage(content=SYSTEM_PROMPT),
    HumanMessage(content="I have severe headaches."),
    AIMessage(content="I understand you're experiencing severe headaches. "
                      "Can you tell me more about the duration and location?"),
    HumanMessage(content="It's been 5 days, left side of head."),
    AIMessage(content="Thank you. Any other symptoms like nausea or vision changes?"),
    HumanMessage(content="Yes, blurred vision and nausea."),
    AIMessage(content="I see. Do you have any MRI or scan results?"),
    HumanMessage(content="Yes, the MRI shows white matter hyperintensities."),
    AIMessage(content="Based on the symptoms and MRI findings..."),
    HumanMessage(content="Can you find hospitals near me in Boston?"),
    AIMessage(content="Here are some hospitals near Boston..."),
    HumanMessage(content="Please save this case."),
    AIMessage(content="Case has been saved successfully."),
]

print(f"Original message count: {len(long_conversation)}")

# Trim to fit context window
trimmed_messages = trim_conversation_messages(
    long_conversation,
    max_tokens=500
)

print(f"Trimmed message count: {len(trimmed_messages)}")
print(f"\n📨 Retained Messages:")
for msg in trimmed_messages:
    role = msg.__class__.__name__.replace("Message", "")
    print(f"  [{role}]: {msg.content[:100]}...")

✂️ Message Trimming Demonstration
====================================================================================================
Original message count: 13
Trimmed message count: 13

📨 Retained Messages:
  [System]:
You are a Multi-Modal Medical AI Assistant Agent. Your role is to help
analyze patient cases based ...
  [Human]: I have severe headaches....
  [AI]: I understand you're experiencing severe headaches. Can you tell me more about the duration and locat...
  [Human]: It's been 5 days, left side of head....
  [AI]: Thank you. Any other symptoms like nausea or vision changes?...
  [Human]: Yes, blurred vision and nausea....
  [AI]: I see. Do you have any MRI or scan results?...
  [Human]: Yes, the MRI shows white matter hyperintensities....
  [AI]: Based on the symptoms and MRI findings......
  [Human]: Can you find hospitals near me in Boston?...
  [AI]: Here are some hospitals near Boston......
  [Human]: Please save this case....
  [AI]: Case has been saved successfully....

In [109]:
# Interactive Chat Interface

def run_interactive_chat():
    """
    Run an interactive chat session with the Medical AI Agent.
    Type 'quit' to exit, 'reset' to clear memory, 'cases' to view stored cases.
    """
    print("=" * 100)
    print("🏥 Medical AI Assistant - Interactive Chat")
    print("=" * 100)
    print("Commands:")
    print("  'quit'   - Exit the chat")
    print("  'reset'  - Clear conversation memory")
    print("  'cases'  - View stored patient cases")
    print("  'memory' - View current memory state")
    print("=" * 100)
    
    while True:
        print()
        user_input = input("👤 You: ").strip()
        
        if not user_input:
            continue
        
        if user_input.lower() == 'quit':
            print("👋 Goodbye! Remember to consult a real doctor.")
            break
        
        if user_input.lower() == 'reset':
            memory.clear()
            print("🔄 Memory cleared!")
            continue
        
        if user_input.lower() == 'cases':
            if os.path.exists(CSV_FILE_PATH):
                df = pd.read_csv(CSV_FILE_PATH)
                print(f"\n📊 Stored Cases ({len(df)} total):")
                print(df[['case_id', 'timestamp', 'patient_symptoms']].to_string())
            else:
                print("No cases stored yet.")
            continue
        
        if user_input.lower() == 'memory':
            mem_data = memory.load_memory_variables({})
            history = mem_data.get("chat_history", [])
            if not history:
                print("(empty)")
            else:
                for idx, entry in enumerate(history, start=1):
                    if isinstance(entry, dict):
                        user_text = entry.get("inputs", {}).get("input", "")
                        ai_text = entry.get("outputs", {}).get("output", "")
                        print(f"\nTurn {idx} User: {user_text[:120]}...")
                        print(f"Turn {idx} AI: {ai_text[:120]}...")
                    else:
                        role = entry.__class__.__name__.replace("Message", "")
                        content = getattr(entry, "content", str(entry))
                        print(f"  [{role}]: {content[:120]}...")
            continue
        
        # Run agent
        try:
            response = agent_executor.invoke({
                "messages": [{"role": "user", "content": user_input}]
            })
            response_text = response.get("output")
            if response_text is None and "messages" in response:
                response_text = response["messages"][-1].content
            if response_text is None:
                response_text = str(response)

            memory.save_context(
                {"input": user_input},
                {"output": response_text}
            )

            print(f"\n🤖 Assistant: {response_text}")
        except Exception as e:
            print(f"\n❌ Error: {str(e)}")

In [110]:
# Start the interactive chat
run_interactive_chat()

====================================================================================================
🏥 Medical AI Assistant - Interactive Chat
====================================================================================================
Commands:
  'quit'   - Exit the chat
  'reset'  - Clear conversation memory
  'cases'  - View stored patient cases
  'memory' - View current memory state
====================================================================================================


📊 Stored Cases (14 total):
                case_id                   timestamp                                                                                                                                                   patient_symptoms
0   CASE-20260424145722  2026-04-24T14:57:22.590459                                                                                                                                    Severe headache, blurred vision
1   CASE-20260424145731  2026-04-24T14:57:31.308154                                                                                                                                    Severe headache, blurred vision
2   CASE-20260424145959  2026-04-24T14:59:59.546426                                                                                                                                    Severe headache, blurred vision
3   CASE-20260424150637  2026-04-24T15:06:37.689787                                                                                                                                    Severe headache, blurred vision
4   CASE-20260424151525  2026-04-24T15:15:25.900821                                                                                                                                    Severe headache, blurred vision
5   CASE-20260424152157  2026-04-24T15:21:57.890933                     Sharp chest pain during physical activity, Shortness of breath, Occasional dizziness, Family history of heart disease, Patient age: 55, Female
6   CASE-20260424152214  2026-04-24T15:22:14.428974     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
7   CASE-20260424152321  2026-04-24T15:23:21.400827                                      Persistent lower back pain for 2 weeks, pain radiating to left leg, numbness in left foot, difficulty walking long distances.
8   CASE-20260424152331  2026-04-24T15:23:31.332173  Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker
9   CASE-20260424152635  2026-04-24T15:26:35.311464     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
10  CASE-20260424154214  2026-04-24T15:42:14.286914                                                                                                                                    Severe headache, blurred vision
11  CASE-20260424154222  2026-04-24T15:42:22.682278     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
12  CASE-20260424154233  2026-04-24T15:42:33.520857                     Sharp chest pain during physical activity, Shortness of breath, Occasional dizziness, Family history of heart disease, Patient age: 55, Female
13  CASE-20260424154242  2026-04-24T15:42:42.578782  Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker


Turn 1 User: ## Patient Symptoms:

    - Persistent headache for 5 days (left temporal region)
    - Blurred vision in left eye
    -...
Turn 1 AI: ### 📋 Case Summary
- **Symptoms**: Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mi...

Turn 2 User: ## Patient Symptoms:

    - Sharp chest pain during physical activity
    - Shortness of breath
    - Occasional dizzine...
Turn 2 AI: ### 📋 Case Summary
- **Symptoms**:
  - Sharp chest pain during physical activity
  - Shortness of breath
  - Occasional...

Turn 3 User: ## Patient Symptoms:

    - Persistent lower back pain for 2 weeks
    - Pain radiates to left leg
    - Numbness in lef...
Turn 3 AI: ### 📋 Case Summary
- **Symptoms**: Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left f...

🔄 Memory cleared!


📊 Stored Cases (14 total):
                case_id                   timestamp                                                                                                                                                   patient_symptoms
0   CASE-20260424145722  2026-04-24T14:57:22.590459                                                                                                                                    Severe headache, blurred vision
1   CASE-20260424145731  2026-04-24T14:57:31.308154                                                                                                                                    Severe headache, blurred vision
2   CASE-20260424145959  2026-04-24T14:59:59.546426                                                                                                                                    Severe headache, blurred vision
3   CASE-20260424150637  2026-04-24T15:06:37.689787                                                                                                                                    Severe headache, blurred vision
4   CASE-20260424151525  2026-04-24T15:15:25.900821                                                                                                                                    Severe headache, blurred vision
5   CASE-20260424152157  2026-04-24T15:21:57.890933                     Sharp chest pain during physical activity, Shortness of breath, Occasional dizziness, Family history of heart disease, Patient age: 55, Female
6   CASE-20260424152214  2026-04-24T15:22:14.428974     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
7   CASE-20260424152321  2026-04-24T15:23:21.400827                                      Persistent lower back pain for 2 weeks, pain radiating to left leg, numbness in left foot, difficulty walking long distances.
8   CASE-20260424152331  2026-04-24T15:23:31.332173  Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker
9   CASE-20260424152635  2026-04-24T15:26:35.311464     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
10  CASE-20260424154214  2026-04-24T15:42:14.286914                                                                                                                                    Severe headache, blurred vision
11  CASE-20260424154222  2026-04-24T15:42:22.682278     Persistent headache for 5 days (left temporal region), Blurred vision in left eye, Mild nausea in the morning, Difficulty concentrating, Patient age: 45, Male
12  CASE-20260424154233  2026-04-24T15:42:33.520857                     Sharp chest pain during physical activity, Shortness of breath, Occasional dizziness, Family history of heart disease, Patient age: 55, Female
13  CASE-20260424154242  2026-04-24T15:42:42.578782  Persistent lower back pain for 2 weeks, Pain radiates to left leg, Numbness in left foot, Difficulty walking long distances, Patient age: 38, Male, Office worker

(empty)

👋 Goodbye! Remember to consult a real doctor.